name = "jrx"
version = "0.0.3"
authors = [
    "Ramon Esparza <mental12345>",
]

[builds.raspPi] 
   arch = "arm64"
   os = "linux"

[builds.release]
   arch = "amd64"
   os = "linux"
   flags = "-ldflags= -s -w"

[builds.dev]
   arch = "amd64"
   os = "linux"