pipeline {
    agent any
    environment {
        // Add environment variables if needed
    }
    stages {
        stage('Checkout') {
            steps { 
                git 'my-go-project.git'
            }
        }
        stage('Build') {
            steps {
                sh 'go mod tidy'
                sh 'go build .'
            }
        }
        stage('Test') {
            steps {
                sh 'go test -v .'
            }
        }
    }
}