name = "{{.ProjectName}}"
version = "0.0.1"
authors = [
    "Author Name",
]

[builds.release] 
    arch = "amd64"
    os = "linux"
    flags = "-ldflags= -s -w"



[builds.dev] 
    arch = "arm64"
    os = "linux"
    