name: "build"
on: 
  push:
    branches-ignore: 
      - main
    
jobs:
  build-dev:
    runs-on: ubuntu-latest
    steps: 
      - name: "setup-go"
        uses: actions/setup-go@v5
        with:
          check-latest: true
      - name: "Checkout code"
        uses: actions/checkout@v4
      - name: "Run build"
        run: go build -o jrx .
        shell: bash
      - uses: actions/upload-artifact@v4
        with:
          name:  jrx 
          path:  ./jrx