name: "jrx release"

on: 
  push:
    tags:
      - 'v*.*.*'
    
jobs:
  build-release:
    runs-on: ubuntu-latest
    steps: 
      - name: "setup-go"
        uses: actions/setup-go@v3
        with:
          go-version: '^1.20'
      - run: go version
        shell: bash
      - name: "Checkout code"
        uses: actions/checkout@v3
      - name: "Run builds release"
        run: |
            make compile
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            bin/jrx-freebsd-amd64
            bin/jrx-linux-amd64
            bin/jrx-linux-arm64
            bin/jrx-darwin-amd64
            bin/jrx-darwin-m1